module.exports = {

  "name": "Leuven-City-Hall-Demo",

  "root": "/demo/Leuven-City-Hall-Demo",

  "images": [
    { "id": 0, "name": "000", "extension": ".png" },
    { "id": 1, "name": "001", "extension": ".png" },
    { "id": 2, "name": "002", "extension": ".png" },
    { "id": 3, "name": "003", "extension": ".png" },
    { "id": 4, "name": "004", "extension": ".png" },
    { "id": 5, "name": "005", "extension": ".png" },
    { "id": 6, "name": "006", "extension": ".png" }
  ],

  "desc": '<p>This demo is created from Leuven cityhall image set (<a href="http://cvlab.epfl.ch/data/strechamvs" target="_blank">source</a>).</p><p>Structure-from-Motion of this demo is complete:</p><p>SIFT features are generated from WebSIFT (WebSFM&#39;s javascript implementation of SIFT).</p><p>Feature matches are generated by WebMatcher (WebSFM&#39;s javascript implementation of kd-tree based ANN matcher).</p><p>Sparse reconstruction is recovered by WebRegister (WebSFM&#39;s javascript implementation of Bundler and Sparse Bundle Adjustment), the initial pair of camera is still unstable.</p><p>Dense reconstruction is generated by Yasutaka Furukawa&#39;s PMVS (<a href="http://www.di.ens.fr/pmvs/">source</a>), WebSFM&#39;s implementation of PMVS is still under construction.</p>',

  "entries": ["image", "feature", "match", "calibration", "mvs"]

};